project:
  type: website
  output-dir: docs

website:
  title: "Caitlin Nordheim-Maestas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true #every page will have a table of contents by default
    page-layout: full

editor: visual

