project:
  type: website
  output-dir: docs

website:
  title: "Caitlin Nordheim-Maestas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: Research.qmd
      - href: Mentoring.qmd
        text: Mentorship

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true #every page will have a table of contents by default
    page-layout: full

editor: source


