---
title: "Scientific Outreach & Academic Service"
---

•	UCSB EEMB Undergraduate Research Symposium Planning Committee – 2021-Present
o	General Member: 2024 Symposium
o	President: 2023 Symposium
o	Treasurer: 2022 Symposium

add in SEEDS Abstract workshop and link to blog posts about prepping a talk and making a poster when I make them. 

Link to website, link to publication, list invited talks

•	Science by the Pint Speaker – 2022 & 2023

BUHS WRCC talk

CEC career panel
•	UC California Ecology and Conservation Course Research and Career Panel Presenter – 2023
•	UC California Ecology and Conservation Course Research and Career Panel Presenter – 2021

UCSB Academic service
•	UCSB EEMB Graduate Mentorship Program Mentor – 2022-Present
•	UCSB EEMB Graduate Student Advisory Council (GSAC) 2021-2023
o	Outreach Subcommittee Member: 2021-2023
•	UCSB EEMB Graduate Research Symposium Planning Committee – 2022-2023
o	Treasurer: 2023 Symposium
o	General Member: 2022 Symposium
•	UCSB EEMB Undergraduate Lab Open House Volunteer – 2022 & 2024


•	University of Pittsburgh Survivor Support Network Member – 2020 - 2021
•	Pitt Biological Sciences SciTech Volunteer – 2020
•	Tampa Middle School Science Fair Volunteer Judge – Spring 2019 
•	University of Tampa PEACE Community Outreach Committee Member – 2015 
