---
title: "Publications"
---

#### Please see my [Google Scholar profile](https://scholar.google.com/citations?user=jV3Mol8AAAAJ&hl=en) for the most up-to-date publication list

## Accepted
<ol reversed>

<li>M.P. Heard, **C.L. Nordheim**, C. McKinley, Z.L. Zilz, V.A. Jones, B.A. Vincent, and E.M. Caves. 2023. Excluded Identity Retention in STEM: A Roadmap for Inclusive Undergraduate Research Symposia. [*Oceanography*]{.underline}: 36(4). <https://doi.org/10.5670/oceanog.2024.116> {{< fa file >}} [PDF](paper-pdfs/oceanography-2023.pdf)

<li>T.A. McMahon, **C.L. Nordheim**, S.E. Detmering, P.T.J. Johnson, J.R. Rohr, and D. Civitello. 2023. *Pseudacris regilla* metamorphs acquire resistance to a deadly pathogen after exposure to the killed fungus. [*Diseases of Aquatic Organisms*]{.underline}: 155:193-198. <https://doi.org/10.3354/dao03753> {{< fa file >}} [PDF](paper-pdfs/dao-2023.pdf)

<li>**C.L. Nordheim**, S.E. Detmering, D. Civitello, P.T.J. Johnson, J.R. Rohr, and T.A. McMahon. 2022. Metabolites from the fungal pathogen *Batrachochytrium dendrobatidis* (Bd) reduce Bd load in Cuban treefrog tadpoles. [*Journal of Applied Ecology*]{.underline}: 59, 2398--2403. <https://doi.org/10.1111/1365-2664.14242> {{< fa file >}} [PDF](paper-pdfs/JAE-2022.pdf)

<li>M. Wilber, M. Ohmer, K. Altman, L. Brannelly, V. Saenz-Calderon, E. LeSage, B. LaBumbard, N. McDonnell, Muñiz-Torres, **C.L. Nordheim**, F. Pfab, C.L. Richards-Zawacki, L.A Rollins-Smith, D. Wetzel, D. Woodhams, and C.J. Briggs. 2022. Once a reservoir, always a reservoir? Seasonality affects the pathogen maintenance potential of amphibian hosts. [*Ecology*]{.underline}: 103(9): e3759 <https://doi.org/10.1002/ecy.3759> {{< fa file >}} [PDF](paper-pdfs/Ecology-2022.pdf)

<li>**C.L. Nordheim**, J.M. Grim, and T.A. McMahon. 2021. *Batrachochytrium dendrobatidis* (Bd) Exposure Damages Gill Tissue and Inhibits Crayfish Mass-Specific Metabolic Rate. [*Diseases of Aquatic Organisms*]{.underline}: 146: 67--73. <https://doi.org/10.3354/dao03623> {{< fa file >}} [PDF](paper-pdfs/dao-2021.pdf)

<li>T.A. McMahon, **C.L. Nordheim**, and D.M. Prokopiak. 2021. Freshwater Snails and the Green Algae Cladophora are Likely Not Hosts of *Batrachochytrium dendrobatidis*. [*Freshwater Biology*]{.underline}: 66: 582-- 586. <https://doi.org/10.1111/fwb.13662> {{< fa file >}} [PDF](paper-pdfs/Freshwater Biology-2021.pdf)

</ol>

## In Review

-   V. Saenz, A.Q. Byrne, M.E.B. Ohmer T.T. Hammond, L.A. Brannelly, K.A. Altman, M. Kosowsky, **C.L. Nordheim**, E.B. Rosenblum and C.L. Richards-Zawacki. Landscape-scale drivers of spatial dynamics and genetic diversity in an emerging wildlife pathogen.


