---
title: "Teaching"
editor: 
  markdown: 
    wrap: 72
---

## University of California, Santa Barbara

-   Biometry Teaching Assistant (EEMB 146; 2 sections, Winter 2024): led
    computer labs, graded assignments, led final projects on independent
    data analysis.

-   Aquatic Communities Teaching Assistant (EEMB 142A; 4 sections, Fall
    2023): led paper discussion groups, graded assignments and exams,
    led final project paper critiques.

-   Biometry Teaching Assistant (EEMB W 146; 1 section, Spring 2023):
    led computer labs, graded assignments, led final projects on
    independent data analysis.

-   Biometry Teaching Assistant (EEMB 146; 2 sections, Winter 2023): led
    computer labs, graded assignments, led final projects on independent
    data analysis.

-   Briggs Lab Undergraduate Journal Club Co-Leader (EEMB 194BC: 2
    sections, 2021 - 2022): Facilitated and led paper discussions, and
    designed a module on finding, reading, and presenting journal
    articles.

## The University of Pittsburgh

-   Education Outreach Curriculum Development: developed a teaching
    module for elementary through secondary school about amphibian
    disease ecology through the University of Pittsburgh.

-   Foundations of Biology II Grader (BIOSC 0160: 1 section, 2020):
    assisted with grading weekly assignments and preparing remote
    coursework at The University of Pittsburgh.

## The University of Tampa

-   Biology Curriculum Development: developed a capture-mark-recapture
    laboratory module implemented in Ecology course (BIO 212, 2017) at
    the University of Tampa.

-   Parasitology Lab Undergraduate Teaching Assistant (BIO 317: 2
    sections, 2019) assisted course instructor with laboratory and
    solution preparation, and assisted students with their classwork and
    independent projects at the University of Tampa.

-   Ecology Lab Undergraduate Teaching Assistant (BIO 212: 3 sections,
    2017): assisted course instructor with laboratory preparation, field
    equipment calibration, input and organized data, assisted students
    with questions at the University of Tampa.

-   Scanning Electron Microscopy Lab Undergraduate Teaching Assistant
    (BIO 390: 1 section, 2018): assisted course instructor with
    laboratory and solution preparation, ran open laboratory, assisted
    students with their classwork and independent projects at the
    University of Tampa.

-   Biology II Head Undergraduate Lab Teaching Assistant and Lab
    Coordinator (BIO 199: 2 sections, 2017 – 2018): assisted and trained
    new teaching assistants, ran open laboratory, answered student
    questions, assisted course instructor with laboratory preparation,
    graded weekly quizzes and exams at the University of Tampa.

-   Biology II Lab Undergraduate Teaching Assistant (BIO 199: 2
    sections, 2016 - 2017): assisted course instructor with grading,
    laboratory preparation, and assisted students in open laboratory at
    the University of Tampa.

-   Biology I Lab Undergraduate Teaching Assistant (BIO 198: 2 sections,
    2016): assisted the course instructor with grading, laboratory
    preparation, solution preparation, and assisted students by
    answering questions at the University of Tampa.

## Bonnyvale Environmental Education Center

-   Environmental Education Camp Counselor (2 summers, 2016 & 2017):
    designed lesson plans, instructed children aged 4-12 in the field on
    biology, ecology, and conservation at the [Bonnyvale Environmental
    Education Center](https://www.beec.org/) in Brattleboro, Vermont.
